### ISSUE TITLE
Softlock on N3DSXL

### ISSUE THREAD

**Issue by MixedVictor** [EnergeticBark/OpenTTD-3DS#2]
Hello i was to play openttd on my new 3ds xl i opened the game and it just softlocks on a black screen rosalina menu wont open and the only way to shut down is pressing the power button. Please fix i like this game and i want to play it on my 3ds 😢

**Comment by EnergeticBark** [comment]
If you're getting a black screen as soon you launch the game then it's just loading. Loading at the start can take quite a while, try waiting ~2 minutes.

**Comment by MixedVictor** [comment]
Ok thanks just taked some minutes
